In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('/content/emails.csv.zip')

In [3]:
df

,text,spam
0,Subject: naturally irresistible your corporate...,1
1,Subject: the stock trading gunslinger fanny i...,1
2,Subject: unbelievable new homes made easy im ...,1
3,Subject: 4 color printing special request add...,1
4,"Subject: do not have money , get software cds ...",1
...,...,...
5723,Subject: re : research and development charges...,0
5724,"Subject: re : receipts from visit jim , than...",0
5725,Subject: re : enron case study update wow ! a...,0
5726,"Subject: re : interest david , please , call...",0


In [4]:
df['spam'].value_counts()

,count
spam,
0,4360
1,1368


In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df

,text,spam
0,Subject: naturally irresistible your corporate...,1
1,Subject: the stock trading gunslinger fanny i...,1
2,Subject: unbelievable new homes made easy im ...,1
3,Subject: 4 color printing special request add...,1
4,"Subject: do not have money , get software cds ...",1
...,...,...
5723,Subject: re : research and development charges...,0
5724,"Subject: re : receipts from visit jim , than...",0
5725,Subject: re : enron case study update wow ! a...,0
5726,"Subject: re : interest david , please , call...",0


In [7]:
df['spam'].value_counts()

,count
spam,
0,4327
1,1368


In [8]:
df.isnull().sum()

,0
text,0
spam,0


In [9]:
x = df.text.values

In [10]:
y = df.spam.values

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtrain,ytrain,ytest = train_test_split(x,y,test_size=.2)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv = CountVectorizer()

In [15]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# ১. xtrain-কে ক্লিন করে নেওয়া
xtrain = pd.Series(xtrain).fillna('').astype(str)

# ২. Vectorizer কল করা
cv = CountVectorizer()

# ৩. ট্রান্সফর্ম করে 새로운 ভ্যারিয়েবল (X_train_cv)-এ রাখা
X_train_cv = cv.fit_transform(xtrain)

# ৪. ফলাফল দেখা
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
model = MultinomialNB()

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# ১. ডেটাসেটে কোনো ফাঁকা ঘর থাকলে তা পূরণ করা (x এবং y কলামের নাম আপনার অনুযায়ী মিলিয়ে নিন)
# ধরে নিচ্ছি আপনার ফিচার x এবং টার্গেট y
df = df.dropna(subset=['text', 'spam']) # বা যে কলামে টেক্সট ও লেবেল আছে

# ২. সঠিকভাবে ডেটা স্প্লিট করা
xtrain, xtest, ytrain, ytest = train_test_split(df['text'], df['spam'], test_size=0.2, random_state=42)

# ৩. টেক্সট ভেক্টরাইজেশন (সবকিছুকে স্ট্রিং নিশ্চিত করে)
cv = CountVectorizer()
X_train_cv = cv.fit_transform(xtrain.astype(str))

# ৪. মডেল ট্রেনিং
model = MultinomialNB()
model.fit(X_train_cv, ytrain)

MultinomialNB()

In [30]:
x_test = cv.transform(xtest)

In [33]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
model.score(x_test,ytest)

0.9912203687445127

In [45]:
emails = ['Hey,How are you?','i am looking you','you are a faltu','you win a iphone for free']

In [46]:
cv_emails = cv.transform(emails)


In [47]:
model.predict(cv_emails)

array([0, 0, 0, 1])